version: '3.3'

services:
  filebeat:
    build:
      context: .
    user: root
    environment:
      LOGSTASH_URL: ${DOCKER_LOCALHOST}:5044
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/log:/target/logs:ro